# Restaurant_Reviews_PYTHON_project

In [41]:
import numpy as np
import pandas as pd
import os

In [45]:
# Importing the dataset
dataset = pd.read_csv('C:\\Users\\Poorna\\Desktop\\SYNXA\\Restaurant_Review_Analysis-master\\Restaurant_Review_Analysis-master\\Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)
dataset

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
5       Now I am getting angry and I want my damn pho.      0
6                Honeslty it didn't taste THAT fresh.)      0
7    The potatoes were like rubber and you could te...      0
8                            The fries were great too.      1
9                                       A great touch.      1
10                            Service was very prompt.      1
11                                  Would not go back.      0
12   The cashier had no care what so ever on what I...      0
13   I tried the Cape Cod ravoli, chicken, with cra...      1
14   I was disgusted because I was pretty sure that...      0
15   I was shocked because no signs indicate cash o...      0
16                                 Highly recommended.      1
17              Waitress was a little slow in service.      0
18   This place is not worth your time, let alone V...      0
19                                did not like at all.      0
20                                 The Burrittos Blah!      0
21                                  The food, amazing.      1
22                               Service is also cute.      1
23   I could care less... The interior is just beau...      1
24                                  So they performed.      1
25   That's right....the red velvet cake.....ohhh t...      1
26          - They never brought a salad we asked for.      0
27   This hole in the wall has great Mexican street...      1
28   Took an hour to get our food only 4 tables in ...      0
29                   The worst was the salmon sashimi.      0
..                                                 ...    ...
970  I immediately said I wanted to talk to the man...      0
971                    The ambiance isn't much better.      0
972  Unfortunately, it only set us up for disapppoi...      0
973                              The food wasn't good.      0
974  Your servers suck, wait, correction, our serve...      0
975      What happened next was pretty....off putting.      0
976  too bad cause I know it's family owned, I real...      0
977               Overpriced for what you are getting.      0
978               I vomited in the bathroom mid lunch.      0
979  I kept looking at the time and it had soon bec...      0
980  I have been to very few places to eat that und...      0
981  We started with the tuna sashimi which was bro...      0
982                            Food was below average.      0
983  It sure does beat the nachos at the movies but...      0
984       All in all, Ha Long Bay was a bit of a flop.      0
985  The problem I have is that they charge $11.99 ...      0
986  Shrimp- When I unwrapped it (I live only 1/2 a...      0
987     It lacked flavor, seemed undercooked, and dry.      0
988  It really is impressive that the place hasn't ...      0
989  I would avoid this place if you are staying in...      0
990  The refried beans that came with my meal were ...      0
991         Spend your money and time some place else.      0
992  A lady at the table next to us found a live gr...      0
993            the presentation of the food was awful.      0
994           I can't tell you how disappointed I was.      0
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [46]:
# Cleaning the texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Poorna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [47]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values

In [49]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [50]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

# Predicting the Test set results

In [52]:

y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1], dtype=int64)

In [62]:
t=pd.DataFrame(y_pred,columns=['preditions'])
t

     preditions
0             1
1             1
2             1
3             0
4             0
5             1
6             1
7             1
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            0
17            0
18            0
19            1
20            0
21            0
22            1
23            1
24            1
25            0
26            1
27            1
28            1
29            0
..          ...
170           0
171           1
172           1
173           0
174           0
175           1
176           0
177           1
178           0
179           0
180           1
181           0
182           0
183           1
184           0
185           1
186           0
187           1
188           0
189           1
190           1
191           0
192           1
193           1
194           1
195           0
196           1
197           1
198           1
199           1

[200 rows x 1 columns]

In [64]:
t['preditions'].value_counts()

1    133
0     67
Name: preditions, dtype: int64

In [65]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,roc_auc_score,roc_curve,auc

accuracy=accuracy_score(y_test, classifier.predict(X_test))
accuracy

0.73

In [54]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55, 42],
       [12, 91]], dtype=int64)